[build]
  publish = ".vitepress/dist"
  command = "npm run docs:build"

[build.environment]
  NODE_VERSION = "18"

# HTTPS redirect for custom domain
[[redirects]]
  from = "http://blogs.northernscript.jp/*"
  to = "https://blogs.northernscript.jp/:splat"
  status = 301
  force = true

# Netlify domain redirect to custom domain
[[redirects]]
  from = "https://northernscript.netlify.app/*"
  to = "https://blogs.northernscript.jp/:splat"
  status = 301
  force = true

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run docs:dev"
  port = 5173
  publish = ".vitepress/dist"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"