[build]
  publish = ".vitepress/dist"
  command = "npm run docs:build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run docs:dev"
  port = 5173
  publish = ".vitepress/dist"